proto: "openocd"
openocd_conf: "../openocd_scripts/microbit.ocd"
ivt_address: 0x20000000
memory_map:
    ivt: {"base" : 0x00000000, "size" : 0x00001000,  "forwarded" : false}
    rom: {"base" : 0x00018000, "size" : 0x00080000,  "forwarded" : false}
    ram: {"base" : 0x20000000, "size" : 0x00019000,  "forwarded" : false}
    mmio: {"base" : 0x40000000, "size": 0x18000000,  "forwarded" : true}
